import "../scripts/variables.just"

cloudflare_env := '--env=""'
wrangler_flags := f"{{cloudflare_env}}"

build: && postprocess
    cargo bin mdbook build

postprocess:
    cargo run -- postprocess

[positional-arguments]
serve *args:
    cargo bin mdbook serve --watcher native $@

[positional-arguments]
dev *args:
    pnpm exec wrangler {{wrangler_flags}} dev $@

types:
    pnpm exec wrangler {{wrangler_flags}} types worker-configuration.d.ts

upload: build
    pnpm exec wrangler {{wrangler_flags}} versions upload
