[package]
name = "util-testing"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
insta = { workspace = true }
tap = { workspace = true }
