name: Setup docs building
description: ""
inputs:
  token:
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
      with:
        toolchain: stable
      id: rustup

    - uses: pnpm/action-setup@v6
      with:
        version: 11
    - uses: actions/setup-node@v7
      with:
        node-version: 26
        cache: pnpm

    - uses: taiki-e/install-action@v2
      with:
        tool: |
          cargo-binstall
          just@1.56.0

    - uses: tonywu6/cache-hit-please@v1.1.1
      id: cache-rs
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        deps: |
          ${{runner.os}}
          ${{runner.arch}}
          ${{steps.rustup.outputs.cachekey}}
          ${{hashFiles('**/Cargo.toml')}}
          ${{hashFiles('**/Cargo.lock')}}
          ${{github.workflow}}
          ${{github.run_id}}
        path: |
          .bin/
          target/

    - uses: tonywu6/cache-hit-please@v1.1.1
      id: cache-js
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        deps: |
          ${{runner.os}}
          ${{runner.arch}}
          ${{hashFiles('**/package.json')}}
          ${{hashFiles('**/pnpm-lock.yaml')}}
          ${{github.workflow}}
          ${{github.run_id}}
        path: |
          .pnpm-store/
          node_modules/

    - run: pnpm install
      shell: bash
