name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**/Cargo.*"
      - "**/*.rs"
      - "**/*.snap"
      - ".github/workflows/ci.yml"

  pull_request:
    branches:
      - main

  schedule:
    - cron: "32 21 * * 0"
      timezone: America/New_York

  workflow_dispatch:
    inputs:
      windows:
        default: false
        type: boolean
      macos:
        default: false
        type: boolean
      toolchain:
        default: stable
        type: string

env:
  CARGO_TERM_COLOR: always
  MDBOOK_LOG: debug
  RUST_BACKTRACE: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (${{ matrix.platform }})

    if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'release-plz-')) }}
    # don't run on release-plz branches because they are updated only after
    # CI is already successful on main

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        windows:
          - ${{ inputs.windows || false }}
        macos:
          - ${{ inputs.macos || false }}

        exclude:
          - platform: windows-latest
            windows: false
          - platform: macos-latest
            macos: false

      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: ${{ github.event_name == 'schedule' && 'nightly' || inputs.toolchain || 'stable' }}
        id: rustup

      - uses: taiki-e/install-action@v2
        with:
          tool: |
            cargo-binstall@1.19.1
            just@1.51.0

      - uses: tonywu6/cache-hit-please@33199e37604407cf26aadfd1a49d1fc2d1e55081
        id: cache
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          deps: |
            ${{runner.os}}
            ${{runner.arch}}
            ${{steps.rustup.outputs.cachekey}}
            ${{hashFiles('**/Cargo.toml')}}
            ${{hashFiles('**/Cargo.lock')}}
            ${{github.workflow}}
            ${{github.run_id}}
          path: |
            .bin/
            target/

      - name: Prepare binaries
        run: |
          cargo bin -- --install

      - name: Test
        run: |
          just cov

      - uses: actions/upload-artifact@v7
        with:
          name: llvm-cov
          path: target/llvm-cov/html
